//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtdelKadrovvv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public string idExpenses { get; set; }
        public string Сosts { get; set; }
        public string Income { get; set; }
    }
}
