//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace buhgalterWin.databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int id { get; set; }
        public System.DateTime DataTime { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> userid { get; set; }
        public decimal Cost { get; set; }
        public int defectid { get; set; }
    
        public virtual Defect Defect { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
