//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace buhgalterWin.databases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DepoEntities1 : DbContext
    {
        public DepoEntities1()
            : base("name=DepoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Defect> Defect { get; set; }
        public virtual DbSet<Expenses> Expenses { get; set; }
        public virtual DbSet<OrderTicket> OrderTicket { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<StopsTram> StopsTram { get; set; }
        public virtual DbSet<TimeTable> TimeTable { get; set; }
        public virtual DbSet<Tram> Tram { get; set; }
        public virtual DbSet<TramDeffect> TramDeffect { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
