//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace buhgalterWin.databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTicket
    {
        public int id { get; set; }
        public int tramid { get; set; }
        public System.TimeSpan Time { get; set; }
        public int Cost { get; set; }
    
        public virtual Tram Tram { get; set; }
    }
}
